[build]
  # O app está dentro de "frontend"
  base    = "frontend"
  # Usa Yarn e seu script "build": "craco build"
  command = "yarn build"
  # Saída do Create React App/CRACO é "build"
  publish = "build"

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
